// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxoptjeoghycccqqwfya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4b3B0amVvZ2h5Y2NjcXF3ZnlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2OTc1NjUsImV4cCI6MjA2MDI3MzU2NX0.7JAwkj95t0Nqx98cS4ysE-HcIoUzW-8QOqmCt3vQ4Vk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);